description: <small>Example documentation of <a href="https://github.com/competitive-verifier/competitive-verifier">competitive-verifier/competitive-verifier</a></small>
highlightjs-style: routeros
filename-index: true
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
consolidate:
- examples/rust
navigation:
  - name: Index
    link: /competitive-verifier/index.html
  - name: Getting Started
    link: /competitive-verifier/installer.html
    sublist:
      - name: 日本語
        link: /competitive-verifier/installer.ja.html
  - name: Reference
    link: /competitive-verifier/document.html
    sublist:
      - name: 日本語
        link: /competitive-verifier/document.ja.html
  - name: DESIGN(日本語)
    link: /competitive-verifier/DESIGN.html